### PR TITLE
Add license tag to the package.json

### PR DESCRIPTION
**Pull request by cdcarter**
to get rid of a silly npm warning.

### CODE REVIEW

**Comment by BrunoFonzi** [comment]
Hi Christian,

Thank you for your contribution, we appreciate the support.
Unless done already, before we can consider the Pull Request, would you mind following these steps:
https://github.com/salesforce-ux/design-system/blob/winter-16/CONTRIBUTING.md

Once approved, it will be easier to accept future contributions too.
Thank you again.

Bruno

**Comment by cdcarter** [comment]
Whoops. I've contributed to SF Foundation products but not SFDC proper, guess I missed this step! Scanning my contributor form right now. I don't know anyone else to @mention here though.

**Comment by amyleesalesforce** [comment]
@cdcarter Thanks for the PR. We talked it over and turns out we have multiple licenses, so we put some code in today for that. Since it collides with this PR I'm going to close it out.

And, yes, the new license is going to generate a different warning but supposedly the syntax is legit according to https://docs.npmjs.com/files/package.json

**Comment by cdcarter** [comment]
Yeehaw. I think you gave me a demo at Dreamforce, @amyleesalesforce! awesome work all around, to you and your team.

**Pull request closed without merging**
