### PR TITLE
Fix typo in class name.

### PR DESCRIPTION
**Pull request by djanowski**

### CODE REVIEW

**Comment by kaelig** [comment]
Thanks for your contribution; we really appreciate your help.

We do require a signed CLA for any contribution, so before we can merge your pull request you'll need to complete the following steps:
https://github.com/salesforce-ux/design-system/blob/master/CONTRIBUTING.md

The good news is that you only have to do this once. Thanks for contributing, and we look forward to integrating your improvements.

**Comment by djanowski** [comment]
> External contributors will be required to sign a Contributor's License Agreement. You can find this file [here](Salesforce_CLA.pdf). Please sign, scan, and send to [osscore@salesforce.com](mailto:osscore@salesforce.com). We look forward to collaborating with you!

ROFL.

**Comment by kaelig** [comment]
We'll fix it ;) thank you for the good catch!

**Comment by djanowski** [comment]
@kaelig Thank you.

**Pull request closed without merging**
