### PR TITLE
feat(illustrations): Extract illustrations into SVG files.

### PR DESCRIPTION
**Pull request by prescod**
**Changes proposed in this pull request:**

*Illustration files should be easily accessible and standalone for any usage pattern. This commit makes image files which can have their styles overriden, but do have default styles inside of them. They can also be used by copying individual files instead of copying hundreds of lines of SVG.

The PR also includes the file which generated the SVGs.

### CODE REVIEW

**Comment by amateurhuman** [comment]
@prescod You've been invited to the org. Once you accept the invitation you can refresh the CLA check by going to https://cla.salesforce.com/status/salesforce-ux/design-system/pull/610

**Comment by prescod** [comment]
We should be good to go now. Glad to be a member of the team.

I'm also a Salesforce.org employee so as you may have heard, I'm joining the team in another sense as well!

**Comment by stefsullrew** [comment]
Thanks for your contribution @prescod. The values in these files need to be tokens, not hard coded values (especially the branding tokens since these are brandable illustrations). That said, I'm not sure that will work in this case since tokens need to run through the Omakase parser as well as the additional piece that handles the branding changes where needed. That's where the values get replaced with the proper values.

Can you talk me through this? Cheers!

**Comment by prescod** [comment]
Hello Stephanie. Thanks for describing this issue.

Each of them does have a <link> tag which allows a reference to a CSS and that CSS can override some of the main [color-and-stroke-related properties](https://github.com/prescod/design-system/commit/b67ef5aba23bb914c98973bb05966f39f2cf9605)

The [link tag](https://github.com/prescod/design-system/commit/b67ef5aba23bb914c98973bb05966f39f2cf9605#diff-787fe222ea32197076cbaf31cbe583bcR37) is at the end (line 37)after the hard-coded values.  This means that it will allow overrides.

So although the technological mechanism may be different, they are at least as configurable as they were when they were [cut-and-paste markup](https://www.lightningdesignsystem.com/components/illustration/, and dramatically easier to use (in my experience).

They also seem easier to rebrand than the old ones here:

https://github.com/salesforce-ux/design-system/tree/master/assets/images/illustrations

So I feel like we have made a step forward with respect to reusability and brand-ability of these illustrations.

Perhaps you can explain how these illustrations were previously supposed to be used and rebranded? I may have misunderstood.

Does the link tag suffice and if not, can you help me to understand what else precisely needs to be over-ridable in these images?

**Comment by stefsullrew** [comment]
Hi @prescod, sure! (Sorry for the delay, I got this mostly written, then interrupted.)

I feel like you're familiar with design tokens? If not, you (or anyone following along) can see them here: https://www.lightningdesignsystem.com/design-tokens/ Design Tokens are used in place of hard-coded values so that their values can change as the system grows. So instead of `margin-bottom: 1rem;`, we say `margin-bottom: $spacing-xx-large;`. This allows us to do things like change the value for densification if the component needs it (for example, `margin-bottom: $var-spacing-xx-large;` would allow the space to get smaller in denser configurations).

Notice how at the top of the page (under Colors), the first big group of colors all start with `$brand-*` (or `t(brand*` for the Lightning/Aura version of the tokens). Those tokens are used to brand elements so that an admin has the ability to chose the company's colors and override them. They do not have the ability to add overrides to the CSS themselves. So an admin picks a background color, an image if they want, their logo, then they give us their company color. We have an algorithm it runs through to create all the versions and contrasting colors. On platform then, there's a process that replaces the colors, but that's only because of A) the tokens, and B) the CSS is in the monolithic SLDS file that Platform processes.

So by having these hard coded values in the SVG itself, we'd be taking away an admins ability to brand these illustrations since they normally have a CSS rule like this:
```css
.slds-illustration__stroke-primary {
    stroke: $illustration-color-primary;
}
```
The token above is what allow it to be processed and changed by an admin. 

Also, the illustration can't link to an internal CSS file path. Everything gets processed and added to app.css, so linking to the local path of the design system will break.

If a developer wants to override the tokens, they would do that in the token bundle for their app (Aura/Lightning). In LWC there will be another mechanism related to custom CSS properties/variables.

Hope this makes sense? Cheers!

**Comment by stefsullrew** [comment]
@prescod If you want to reach out to me internally via email, etc we can chat further and I can explain more of the internals for you. :)

**Pull request closed without merging**
