### PR TITLE
Full RTL Support

### PR DESCRIPTION
**Pull request by mattgoldspink**
For #308 

Changes proposed in this pull request:
- Full RTL support by generating seperate `.rtl.` stylesheets.
  - Adding directional-scss to flip the styles based on the preset $dir value (see https://github.com/tysonmatanich/directional-scss - MIT licensed)
  - New style sheets created for rtl versions of all stylesheets
  - Existing rules updated to use appropriate mixins, functions and variables.

NOTES
I have assumed that by default anyone using the "rtl" stylesheet will also have set `<html dir="rtl">` on their page. This attribute gives the initial flip for most things (for example flexbox grids are automatically flipped for us).

I have gone through every component in the docs - even those we don't use - and fixed them. To do this I modified the `scripts/gulp/pages.jsx` to create the embedded example iframe with `dir="rtl"` and use the `.rtl` version of the stylesheet. I have NOT checked in this change, so if you want to manually see the rtl versions you'll need to reproduce this:

image

I have left checkbox ticks facing the ltr way (I'm not an expert on rtl languages but what I've seen in the past is a that things like ticks don't change direction just because it's rtl). However the checkbox is position on the alternate side of existing elements.

I did not flip some arrows as I'm not sure if we should create additional CSS rule to use `transform` on these or use the opposite SVG arrow direction (for example on Tree expanding).

Salesforce CLA will be signed shortly.
### Reviewer, please refer to this "definition of done" checklist:
- [X] Tested on **desktop** (see [supported browsers](https://www.lightningdesignsystem.com/faq/#what-browsers-are-supported))
  In Chrome 53.0.2785.116 (64-bit), Firefox 48.0.0.1 (on Mac), IE11 Win7
- [ ] Tested on **mobile** (for responsive or mobile-specific features) - No, which devices should be tested for this?
- [ ] Documentation is up to date - Not yet, I'm happy to do this, but just need some direction as to where this should end up
- [ ] Release notes mention the changes - same as above.

Some sample screenshots:

Activity Timeline
image

Data Tables
image

Process
image

### CODE REVIEW

**Comment by kaelig** [comment]
Thank you @mattgoldspink for putting so much thought into this.

We'll get back to you about this very soon.

**Comment by srohde** [comment]
@mattgoldspink, this looks great. Thank you!
We need a bit of time to review it and decide were it fits into the schedule.

**Comment by istiti** [comment]
thanks

**Comment by kaelig** [comment]
Closing this as we are revamping how the framework gets built and will be unable to release it in Spring ’17.

We'll still consider the code in this PR as we implement full RTL support across more components.

Thanks again for putting the time and effort into it, @mattgoldspink!

**Pull request closed without merging**
