### PR TITLE
Fix .slds-item for .slds-post__footer-action

### PR DESCRIPTION
**Pull request by danilobrinu**
Fix .slds-item for .slds-post__footer-action to center button in space when viewport is medium

```css
.slds-post__footer-actions-list .slds-item {
  display: flex;
  justify-content: center;
}
```

Remove margin right when viewport is medium 

```css
@media (max-width: 48em) {
  .slds-post__footer-actions-list .slds-item {
    margin-right: 0;
  }
}
```

Changes proposed in this pull request:

* Center buttons when viewport is medium and remove margin-right

### Reviewer, please refer to this "definition of done" checklist:

* [x] Tested on **desktop** (see [supported browsers](https://www.lightningdesignsystem.com/faq/#what-browsers-are-supported))
* [x] Tested on **mobile** (for responsive or mobile-specific features)
* [x] Confirm **Accessibility**
* [x] Documentation is up to date
* [ ] Release notes mention the changes

⚠️ Once this pull request is merged, please merge the code into other development branches:
[Merge branch 'spring-17' into summer-17](http://bit.ly/2fjT4LY)
[Merge branch 'summer-17' into winter-18](http://bit.ly/2mbKAbV)

### CODE REVIEW

**Comment by danilobrinu** [comment]
@brandonferrua some comment about this ?

**Comment by danilobrinu** [comment]
@kaelig can you review this ?

**Comment by danilobrinu** [comment]
@engai can you review this ??

**Comment by alexiscordova** [comment]
Thanks for your pull request. Unfortunately, these types of changes need to be run through the proper design channels, and this is being addressed through on our ongoing mobile efforts.

**Pull request closed without merging**
